// Exercise the actual packaged main/preload/React application with an isolated profile.
const { app, BrowserWindow } = require('electron')
const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const root = path.resolve(__dirname, '..')
const appRoot = process.argv.includes('--packaged') ? path.join(root, 'release', 'win-unpacked', 'resources', 'app.asar') : root
const output = path.join(root, 'outputs', 'qa')
fs.mkdirSync(output, { recursive: true })
app.setPath('userData', fs.mkdtempSync(path.join(output, 'groups-profile-')))
const market = require(path.join(appRoot, 'dist-electron', 'market.js'))
market.fetchQuotes = async items => items.map(item => ({ ...item, price: 12, previousClose: 10, change: 2, changePercent: 20, mainNetInflow: null, mainNetRatio: null, superLargeNet: null, largeNet: null, amount: null, volumeRatio: null, actualTurnoverRate: null, bid1Price: null, bid1Volume: null, ask1Price: null, ask1Volume: null, updatedAt: new Date().toISOString(), status: 'live' }))
market.searchStocks = async () => [{ market: 'SZ', code: '000002', name: '分组新增股票' }]
const store = require(path.join(appRoot, 'dist-electron', 'store.js'))
store.defaults.watchlist[1] = { ...store.defaults.watchlist[1], costPrice: 10, holdingLots: 5 }
const errors = []; const checks = []
app.on('web-contents-created', (_, contents) => {
  contents.on('render-process-gone', (_, details) => errors.push(details.reason))
  contents.on('preload-error', (_, __, error) => errors.push(error.message))
})
require(path.join(appRoot, 'dist-electron', 'main.js'))
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
const check = name => { checks.push(name); console.log('PASS ' + name) }
async function run() {
  await app.whenReady()
  let win
  for (let i = 0; i < 100; i++) { win = BrowserWindow.getAllWindows()[0]; if (win && !win.webContents.isLoadingMainFrame()) break; await sleep(50) }
  assert(win)
  const js = code => win.webContents.executeJavaScript(code, true)
  const wait = async code => { for (let i = 0; i < 140; i++) { if (await js(code)) return; await sleep(50) }; throw Error('Timeout: ' + code) }
  const click = selector => js(`document.querySelector(${JSON.stringify(selector)}).click()`)
  const input = (selector, value) => js(`(() => { const e = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(e, ${JSON.stringify(value)}); e.dispatchEvent(new Event('input', { bubbles: true })); })()`)
  await wait("!!window.marketFloat && !!document.querySelector('.decoy-actions')")
  await js('window.marketFloat.setDecoy(false)'); await wait("document.querySelectorAll('.stock-main').length === 3")
  assert.equal((await js('window.marketFloat.loadState()')).watchGroups.length, 0)
  check('old profile opens with all original stocks and no groups')
  await click('[title="管理自选分组"]'); await input('.group-create input', '长线'); await click('.group-create button')
  await wait("window.marketFloat.loadState().then(s => s.watchGroups.length === 1)")
  const groupId = (await js('window.marketFloat.loadState()')).watchGroups[0].id
  await input('.group-create input', '长线'); await click('.group-create button')
  await wait("document.querySelector('.group-panel .error')?.innerText.includes('已存在')")
  assert.equal((await js('window.marketFloat.loadState()')).watchGroups.length, 1)
  check('group creation rejects duplicates')
  await click('[title="关闭分组管理"]')
  await js(`(() => { const e=document.querySelector('[data-stock-id="SH.600519"] .stock-group-picker select'); e.value=${JSON.stringify(groupId)};e.dispatchEvent(new Event('change',{bubbles:true})); })()`)
  await wait(`window.marketFloat.loadState().then(s => s.watchlist.find(v => v.code === '600519').groupId === ${JSON.stringify(groupId)})`)
  await click(`[data-group-filter="${groupId}"]`)
  await wait("document.querySelectorAll('.stock-main').length === 1")
  assert(await js("!!document.querySelector('[data-stock-id=\"SH.600519\"]')"))
  check('manual assignment and group filter display only the selected stock')
  await click('[title="管理自选分组"]'); await input('.group-manager-row input', '长期持有'); await click('.group-manager-row form button')
  await wait("window.marketFloat.loadState().then(s => s.watchGroups[0].name === '长期持有')")
  assert.equal((await js('window.marketFloat.loadState()')).watchlist.find(v => v.code === '600519').groupId, groupId)
  await click('[title="关闭分组管理"]')
  check('rename retains stock membership')
  await click('.tool-actions .add'); await input('.searchbox input', '000002')
  await wait("!!document.querySelector('.results button')"); await click('.results button')
  await wait("document.querySelectorAll('.stock-main').length === 2")
  assert.equal((await js('window.marketFloat.loadState()')).watchlist.find(v => v.code === '000002').groupId, groupId)
  check('adding stock inside a group assigns it without duplication')
  win.webContents.reload(); await wait("!!document.querySelector('.decoy-actions')")
  await js('window.marketFloat.setDecoy(false)'); await wait("document.querySelectorAll('.stock-main').length === 4")
  await click(`[data-group-filter="${groupId}"]`); await wait("document.querySelectorAll('.stock-main').length === 2")
  check('group and assignments survive renderer reload')
  await click('[title="管理自选分组"]'); await click('.group-manager-row form button[type=button]')
  await wait("!!document.querySelector('.group-delete-confirm button')"); await click('.group-delete-confirm button')
  await wait("window.marketFloat.loadState().then(s => s.watchGroups.length === 0)")
  await click('[title="关闭分组管理"]'); await wait("document.querySelectorAll('.stock-main').length === 4")
  const state = await js('window.marketFloat.loadState()')
  assert(state.watchlist.every(item => !item.groupId)); assert.equal(state.watchlist.find(v => v.code === '600519').costPrice, 10)
  assert.equal(state.watchlist.find(v => v.code === '600519').holdingLots, 5)
  check('delete selected group returns stocks to ungrouped and retains holdings')
  await click('[data-group-filter="ungrouped"]'); await wait("document.querySelectorAll('.stock-main').length === 4")
  assert.deepEqual(errors, [])
  fs.writeFileSync(path.join(output, 'groups-smoke-result.json'), JSON.stringify({ checks, errors, packaged: process.argv.includes('--packaged') }, null, 2))
  app.exit(0)
}
const watchdog = setTimeout(() => { console.error('Group UI smoke timeout', checks, errors); app.exit(1) }, 60000)
run().catch(error => { console.error(error); clearTimeout(watchdog); app.exit(1) })
