import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './alerts.css'
import './theme.css'
import './decoy-v2.css'
import './candlestick.css'
import './hot-rank.css'
import './watch-optimizer.css'
import './intraday.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
